In [3]:
#Python


In [1]:
1+1

2

In [4]:
3*3

9

In [1]:
type(2.2)

float

In [2]:
b = 10
s = 5

In [3]:
print(b/s)

2.0


In [5]:
print(b*s)

50


In [6]:
print(b*s)

50


In [7]:
print("hello jitu")

hello jitu


In [9]:
type('jitu')

str

In [10]:
type('jitu kr')

str

In [9]:
type(10.3)

float

In [12]:
print("python")

python


In [13]:
len("jitendra")

8

In [11]:
f_n='jitu'
l_n='sah'

In [13]:
print("my name is {} and last name is {}".format(last=l_n, first=f_n))

IndexError: tuple index out of range

In [14]:
tru_str.isalu

NameError: name 'tru_str' is not defined

In [15]:
lst=[1,2,3,4,5,32]

In [16]:
min(lst)

1

In [22]:
type([])

list

In [23]:
lst_exam=[]

In [25]:
type(lst_exam)

list

In [31]:
lst=['jitu','kum',2,2,3,4,5]

In [33]:
lst[1:4]

['kum', 2, 2]

In [34]:
lst=['jitu','kum',2,2,3,4,5]

In [17]:
lst.append(["bala","kala"])

In [20]:
lst

[1, 2, 3, 4, 5, 32, ['bala', 'kala']]

In [1]:
## defining an empty set

set_var=set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [2]:
set_var.add("hulk")

In [3]:
print(set_var)

{'hulk'}


In [ ]:
conda install numpy

In [1]:
## initialy let's import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

In [3]:
arr=np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
## multinested array

my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,9,10]
my_lst3=[11,12,13,14,15]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr[:,:]

In [40]:
arr[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [41]:
arr[1:2,2:3]

array([[8]])

In [42]:
arr=np.array(0,10,step=2)

TypeError: data type not understood

In [43]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
arr=np.arange(0,10,step=3)

In [6]:
arr

array([0, 3, 6, 9])

In [8]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [4]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [7]:
#Split the array in 3 parts:
#We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
#You can search an array for a certain value, and return the indexes that get a match.
#To search an array, use the where() method.

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [9]:
#The NumPy ndarray object has a function called sort(), that will sort a specified array.

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [10]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [11]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]
